#!/usr/bin/env escript
%%! -pa ebin -Wall

usage() ->
    io:format('Usage: analyzer~n'),
    io:format('(Uses stdin/stdout.)~n').

main([]) ->
    Stream = '<stdin>',
    String = tool_chain:string_from_input(),
    Output = try process(Stream, String)
    catch
        {tool_chain_exception, invalid_term} -> tool_chain:die(String);
        {_CompilationException, Message}     -> tool_chain:die(Message)
    end,
    tool_chain:term_to_output(Output);
main(_) ->
    usage().

process(Stream, String) ->
    {SourceLines, {ast,ParseTree}} = tool_chain:term_from_string(String),
    {ok, _ParseTree1} = analyzer_driver:analyze(Stream, ParseTree),
    {SourceLines, {ast,ParseTree}}.
