#!/usr/bin/env escript
%%! -pa ebin -Wall

usage() ->
    io:format('Usage: analyzer~n'),
    io:format('(Uses stdin/stdout.)~n').

main([]) ->
    Stream = '<stdin>',
    String = tool_chain:string_from_input(),
    Result = (catch process(Stream, String)),
    case Result of
        {_SourceLines, {ast,_ParseTree}} = Output ->
            tool_chain:term_to_output(Output);
        {analyzer_exception, Message} ->
            tool_chain:die(Message);
        {tool_chain_exception, invalid_term} ->
            tool_chain:die(String);
        UnknownError ->
            tool_chain:die('~p~n', [UnknownError])
    end;
main(_) ->
    usage().

process(Stream, String) ->
    {SourceLines, {ast,ParseTree}} = tool_chain:term_from_string(String),
    {ok, _ParseTree1} = analyzer_driver:analyze(Stream, ParseTree),
    {SourceLines, {ast,ParseTree}}.
