#!/usr/bin/env escript
%%! -pa ebin -Wall

usage() ->
    io:format('Usage: codegen~n'),
    io:format('(Uses stdin/stdout.)~n').

main([]) ->
    Stream = '<stdin>',
    String = tool_chain:string_from_input(),
    Output = try process(Stream, String)
    catch
        {tool_chain_exception, invalid_term} ->
            tool_chain:die(String)
    end,
    tool_chain:term_to_output(Output);
main(_) ->
    usage().

process(Stream, String) ->
    {{source,Lines}, {rtl,RtlCode}} = tool_chain:term_from_string(String),
    {ok, AsmCode} = codegen_driver:generate_code(Stream, RtlCode, Lines),
    {{source,Lines}, {asm,AsmCode}}.
