#!/usr/bin/env escript
%%! -pa ebin

version() ->
    '0.0.1'.

usage() ->
    io:format('Usage: ducc [file]~n'),
    io:format('(Uses stdin if no file given.)~n').

main([]) ->
    String = tool_chain:string_from_input(),
    compile(String);
main(["-v"]) ->
    io:fwrite('ducc ~s~n', [version()]);
main([File]) ->
    String = tool_chain:string_from_file(File),
    compile(String);
main(_) ->
    usage().

compile(String) ->
    Tokens = lexer_driver:tokenize(String),
    ParseTree = parser_driver:parse(Tokens),
    tool_chain:term_to_output(ParseTree).
