#!/usr/bin/env escript
%%! -pa ebin -Wall

usage() ->
    io:format('Usage: lexer~n'),
    io:format('(Uses stdin/stdout.)~n').

main([]) ->
    String = tool_chain:string_from_input(),
    Tokens = lexer_driver:tokenize('<stdin>', String),
    handle_it(Tokens);
main(_) ->
    usage().

handle_it({ok, Tokens}) ->
    tool_chain:term_to_output(Tokens);
handle_it(_Error) ->
    ok.
