#!/usr/bin/env escript
%%! -pa ebin -Wall

usage() ->
    io:format('Usage: parser~n'),
    io:format('(Uses stdin/stdout.)~n').

main([]) ->
    String = tool_chain:string_from_input(),
    Term = tool_chain:term_from_string(String),
    Processor = fun(X) -> process('<stdin>', X) end,
    tool_chain:process_term_or_echo(Processor, Term, String);
main(_) ->
    usage().

process(Stream, Tokens) ->
    {ok, ParseTree} = parser_driver:parse(Stream, Tokens),
    tool_chain:term_to_output(ParseTree).
