#!/usr/bin/env escript
%%! -pa ebin -Wall

main(["-l"]) ->
    test_lexer();
main(["-p"]) ->
    test_parser();
main(["-a"]) ->
    test_analyzer();
main(["-t"]) ->
    test_translator();
main([]) ->
    test_lexer(),
    test_parser(),
    test_analyzer(),
    test_translator().

test_lexer() ->
    io:format("Testing lexer ...~n"),
    lexer_test:test().

test_parser() ->
    io:format("Testing parser ...~n"),
    parser_test:test().

test_analyzer() ->
    io:format("Testing analyzer ...~n"),
    analyzer_test:test().

test_translator() ->
    io:format("Testing translator ...~n"),
    translator_test:test().
