#!/usr/bin/env escript
%%! -pa ebin -Wall

usage() ->
    io:format('usage: runtest [-a|-l|-p|-t]~n').

main(["-l"]) ->
    io:format("Testing lexer ...~n"),
    lexer_test:test();
main(["-p"]) ->
    io:format("Testing parser ...~n"),
    parser_test:test();
main(["-a"]) ->
    io:format("Testing analyzer ...~n"),
    analyzer_test:test();
main(["-t"]) ->
    io:format("Testing translator ...~n"),
    translator_test:test();
main([]) ->
    main(["-l"]),
    main(["-p"]),
    main(["-a"]),
    main(["-t"]);
main(_) ->
    usage().
