#!/usr/bin/env escript
%%! -pa ebin -Wall

usage() ->
    io:format('usage: runtest [-a|-c|-e|-l|-p|-t]~n').

main(["-l"]) ->
    testing(lexer),
    lexer_test:test();
main(["-p"]) ->
    testing(parser),
    parser_test:test();
main(["-a"]) ->
    testing(analyzer),
    analyzer_test:test();
main(["-t"]) ->
    testing(translator),
    translator_test:test();
main(["-c"]) ->
    testing(codegen),
    codegen_test:test();
main(["-e"]) ->
    testing(emitter),
    emitter_test:test();
main([]) ->
    main(["-l"]),
    main(["-p"]),
    main(["-a"]),
    main(["-t"]),
    main(["-c"]);
    main(["-e"]);
main(_) ->
    usage().

testing(Program) ->
    io:format("--- Testing ~s ...~n", [Program]).
